---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [4]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [1]:
def minus_numbers(x, y):
    return x - y

minus_numbers(2,1)

1

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [2]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


<br>
`add_numbers` updated to take an optional flag parameter.

In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


<br>
Assign function `add_numbers` to variable `a`.

In [8]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

b = minus_numbers
b(3,1)

2

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [5]:
type('This is a string')

str

In [6]:
type(None)

NoneType

In [7]:
type(1)

int

In [8]:
type(1.0)

float

In [9]:
type(add_numbers)

function

In [11]:
import pandas as pd
type(pd)

module

In [18]:
import numpy as np
type(np.NaN)
type(np.array)

float

<br>
Tuples are an immutable data structure (cannot be altered).

In [20]:
x = (1, 'a', 2, 'b')
type(x)

tuple

In [26]:
x = (1,2,3,4,5,6)
x = [x]
for a in x:
    print(a)

(1, 2, 3, 4, 5, 6)


In [27]:
x = (1,2,3,4,5,6)
x = list(x)
for a in x:
    print(a)

1
2
3
4
5
6


<br>
Lists are a mutable data structure.

In [28]:
x = [1, 'a', 2, 'b']
type(x)

list

<br>
Use `append` to append an object to a list.

In [30]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3, 3.3]


In [36]:
x.append(4)
print(x)

[1, 'a', 2, 'b', 3.3, 3.3, 3.3, 3.3, 4, 4, 4, 4]


In [38]:
x.clear()
print(x)

[]


In [40]:
x.append(0)
x

[0, 0]

In [41]:
x = [1, 'a', 2, 'b','3.3']
type(x)

list

<br>
This is an example of how to loop through each item in the list.

In [42]:
for item in x:
    print(item)

1
a
2
b
3.3


<br>
Or using the indexing operator:

In [48]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1
    
print('length of x list:' + str(len(x)))
print('length of x list:{}'.format(len(x)))

1
a
2
b
3.3
length of x list:5
length of x list:5


<br>
Use `+` to concatenate lists.

In [49]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [52]:
[1,2] / [3,4]
# only suppot add for list operation
# -,*,/ are not supported between two list

TypeError: unsupported operand type(s) for /: 'list' and 'list'

<br>
Use `*` to repeat lists.

In [53]:
[1]*3

[1, 1, 1]

In [58]:
[1]+2
# still only support *, +,-,/ are not supported

TypeError: can only concatenate list (not "int") to list

In [60]:
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

<br>
Use the `in` operator to check if something is inside a list.

In [64]:
1 in [1, 2, 3]

True

In [66]:
[1, 2] in  [1, 2,3]

False

In [68]:
2 in [1, 2, 3]

True

In [70]:
1 in (1, 2, 3)

True

In [72]:
(1, 2) in (1, 2, 3)

False

In [74]:
(1, 2) in ((1,2), 'a', 'b')

True

In [75]:
for x in ((1,2), 'a', 'b'):
    print(x)

(1, 2)
a
b


<br>
Now let's look at strings. Use bracket notation to slice a string.

In [80]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters
print(x[-1])

T
T
Th
g


<br>
This will return the last element of the string.

In [15]:
x[3:]

's is a string'

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [14]:
x[-4:-2]

'ri'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [21]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 4th element of the string and going all the way to the end.

In [82]:
x[3:]

's is a string'

In [81]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)
print('to' in firstname)


Christopher Brooks
ChristopherChristopherChristopher
True
True


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [19]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
test = 'Dr. Christopher Brooks'
print(test[4:-7])
print(lastname)

Christopher
Christopher
Brooks


<br>
Make sure you convert objects to strings before concatenating.

In [25]:
'Chris' + 2

TypeError: must be str, not int

In [26]:
'Chris' + str(2)

'Chris2'

<br>
Dictionaries associate keys with values.

In [88]:
# a dictionay with elements split by , and key value split by :
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [89]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']
print(x['Kevyn Collins-Thompson'])
x['Kevyn Collins-Thompson']

None


<br>
Iterate over all of the keys:

In [90]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


<br>
Iterate over all of the values:

In [91]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


<br>
Iterate over all of the items in the list:

In [94]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


<br>
You can unpack a sequence into different variables:

In [95]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [96]:
fname

'Christopher'

In [14]:
lname

'Brooks'

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [97]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email, testname = x

<br>
# The Python Programming Language: More on Strings

In [16]:
print('Chris' + 2)

TypeError: must be str, not int

In [98]:
print('Chris' + str(2))

Chris2


<br>
Python has a built in method for convenient string formatting.

In [99]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'
print(sales_record['person'])
print(sales_record['num_items'])
print(sales_record['price'])

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris
4
3.24
Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [107]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    test = csv.DictReader(csvfile)
    mpg = list(csv.DictReader(csvfile))

print(type(test))
mpg[:3] # The first three dictionaries in our list.

<class 'csv.DictReader'>


[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [4]:
len(mpg)

234

<br>
`keys` gives us the column names of our csv.

In [109]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [116]:
# get the first element(a dictionary first)
# then get items of the dictionary 
mpg[0].items()

dict_items([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [118]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [122]:
sum(float(d['cty']) for d in mpg)

3945.00

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [123]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [128]:
cylinders = set(d['cyl'] for d in mpg)
print(cylinders)
test = list(d['cyl'] for d in mpg)
print(test)
len(test)

{'6', '8', '5', '4'}
['4', '4', '4', '4', '6', '6', '6', '4', '4', '4', '4', '6', '6', '6', '6', '6', '6', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '4', '4', '6', '6', '6', '4', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '8', '8', '8', '8', '8', '6', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '6', '6', '6', '6', '8', '8', '6', '6', '8', '8', '8', '8', '8', '6', '6', '6', '6', '8', '8', '8', '8', '8', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '6', '6', '6', '4', '4', '4', '4', '6', '6', '6', '6', '6', '6', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '8', '6', '6', '8', '8', '4', '4', '4', '4', '6', '6', '6', '6', '6', '6', '6', '6', '8', '6', '6', '6', '6', '8', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '6', '6', '6', '8', '4', '4', '4', '4', '6', '6', '6', '4', '4', '4', '4', '6', '6', '6', '4', '4', '4'

234

In [130]:
testlist = [1,2,3,4,4,3,2,1]
print(testlist)
print(set(testlist))

[1, 2, 3, 4, 4, 3, 2, 1]
{1, 2, 3, 4}


<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [232]:
%%timeit -n 100
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

417 µs ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [233]:
%%timeit -n 100
from numpy import mean
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    testlist = [float(d['cty']) for d in mpg if d['cyl'] == c]
    CtyMpgByCyl.append((c, mean(testlist))) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

524 µs ± 68.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [144]:
list(x[0] for x in CtyMpgByCyl)

['8', '6', '5', '4']

<br>
Use `set` to return the unique values for the class types in our dataset.

In [132]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [145]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

<br>
# The Python Programming Language: Dates and Times

In [146]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [150]:
tm.time()

1604281365.68

In [159]:
type(dt.datetime(2020,11,2) - dt.datetime(1970,1,1))

datetime.timedelta

<br>
Convert the timestamp to datetime.

In [160]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2020, 11, 2, 9, 45, 45, 744964)

<br>
Handy datetime attributes:

In [15]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2019, 9, 5, 14, 7, 32)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [161]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

In [164]:
delta = dt.timedelta(100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

In [165]:
dt.timedelta?

<br>
`date.today` returns the current local date.

In [170]:
today = dt.date.today()

In [174]:
help(dt.date)

Help on class date in module datetime:

class date(builtins.object)
 |  date(year, month, day) --> date object
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      Formats self with strftime.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __radd__(self, value, /)
 |      Return value+self.
 |  
 |  __reduce__(...)
 |      __reduce__() -> (cls, state)
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  __rsub__(self, value, /)
 |      Return value-self.
 |  
 |  _

In [169]:
today - delta # the date 100 days ago

datetime.date(2020, 7, 25)

In [175]:
today > today-delta # compare dates

True

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [178]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [179]:
class Teacher:
    
    def set_name(self, new_name):
        self.name = new_name
    def set_subject(self, new_subject):
        self.subject = new_subject

In [181]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))
person.email = 'test@mail.com'
print(person.email)

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information
test@mail.com


In [189]:
teacher = Teacher()
teacher.set_name('English Teacher')
teacher.set_subject('English')

print(teacher.name)
print(teacher.subject)

teacher.gender = 'Male'
print(teacher.gender)

English Teacher
English
Male


<br>
Here's an example of mapping the `min` function between two lists.

In [202]:
store1 = [8.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [201]:
multiplyresult = map(sum, store1, store2)
multiplyresult

<br>
Now let's iterate through the map object to see the values.

In [203]:
for item in cheapest:
    print(item)

8.0
11.0
12.34
2.01


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [204]:
my_function = lambda a, b, c : a + b + c*2

In [205]:
my_function(1, 2, 3)

9

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [207]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension.

In [234]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [237]:
for number in range(8, 10):
    print(number)

8
9


<br>
# The Python Programming Language: Numerical Python (NumPy)

In [238]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [322]:
# a new data type is imported!
# it's array type of numpy
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [323]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [244]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [246]:
m = np.array([7, 8, 9]*3)
m

array([7, 8, 9, 7, 8, 9, 7, 8, 9])

In [247]:
[7, 8, 9] + [10, 11, 12]

[7, 8, 9, 10, 11, 12]

In [248]:
[7, 8, 9]*3

[7, 8, 9, 7, 8, 9, 7, 8, 9]

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [249]:
m.shape

(9,)

<br>
`arange` returns evenly spaced values within a given interval.

In [251]:
# a function named as arrange to get a list
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [254]:
n = n.reshape(5, 3) # reshape array to be 3x5
n

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [262]:
testm = n.reshape(15, 1) # reshape array to be 3x5
testm

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28]])

In [273]:
n = np.arange(0, 30, 2)
n.resize(15, 1)
n

array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18],
       [20],
       [22],
       [24],
       [26],
       [28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [253]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [275]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [280]:
o.resize(1)
o

ValueError: cannot resize this array: it does not own its data

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [281]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [286]:
np.ones?

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [287]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [292]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [293]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [294]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [296]:
np.diag?

<br>
Create an array using repeating list (or see `np.tile`)

In [297]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [300]:
np.repeat([1, 2, 3], 6)

array([1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3])

<br>
#### Combining Arrays

In [304]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [307]:
p*3

array([[3, 3, 3],
       [3, 3, 3]])

In [311]:
test = [[1,1,1],[1,1,1]]
test*3

[[1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1], [1, 1, 1]]

In [313]:
test = [1,2,3]
test*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [315]:
np.vstack([p*123, 3*p])

array([[123, 123, 123],
       [123, 123, 123],
       [  3,   3,   3],
       [  3,   3,   3]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [325]:
np.hstack([p, 2*p, 3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [328]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [331]:
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [332]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [333]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [334]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [340]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array
z

2


array([[ 4,  5,  6],
       [16, 25, 36]])

In [343]:
z = np.hstack([y, y**2])
z

array([ 4,  5,  6, 16, 25, 36])

In [339]:
z = np.vstack([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [344]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [346]:
z.shape

(2, 3)

In [349]:
z.reshape(3,2)

array([[ 4,  5],
       [ 6, 16],
       [25, 36]])

<br>
Use `.T` to get the transpose.

In [350]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [351]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [352]:
z.dtype

dtype('int32')

<br>
Use `.astype` to cast to a specific type.

In [354]:
z = z.astype('f')
print(z)
z.dtype

[[ 4.  5.  6.]
 [16. 25. 36.]]


dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [356]:
a = np.array([-4, -2, 1, 3, 5])

In [357]:
a.sum()

3

In [358]:
a.max()

5

In [359]:
a.min()

-4

In [360]:
a.mean()

0.6

In [361]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [364]:
print(a.argmax())
print(a[a.argmax()])

4
5


In [363]:
a.argmin()

0

<br>
## Indexing / Slicing

In [366]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [367]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [368]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

<br>
Use negatives to count from the back.

In [370]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [371]:
s[-4:-1]

array([ 81, 100, 121], dtype=int32)

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [373]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

<br>
Let's look at a multidimensional array.

In [391]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [375]:
r[2, 2]

14

In [377]:
r[0]

array([0, 1, 2, 3, 4, 5])

<br>
And use : to select a range of rows or columns

In [127]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [128]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [378]:
r[-1, ::2]

array([30, 32, 34])

In [380]:
r[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [403]:
r[r > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 30, 30, 30, 30, 30])

In [387]:
np.ogrid[:3, :4]

[array([[0],
        [1],
        [2]]),
 array([[0, 1, 2, 3]])]

In [400]:
np.where?

In [401]:
np.where(r>10, r, 0)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [404]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [405]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [406]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [407]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [408]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [409]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [413]:
test = np.random.randint(0, 10, (4,3))
test

array([[1, 6, 7],
       [7, 1, 8],
       [8, 9, 6],
       [8, 5, 0]])

In [416]:
test = np.random.randint(0, 10, (4,10))
test

array([[8, 0, 1, 8, 7, 5, 7, 6, 4, 6],
       [5, 2, 2, 6, 3, 7, 8, 6, 1, 2],
       [6, 7, 7, 1, 1, 5, 1, 3, 5, 4],
       [1, 5, 4, 2, 0, 8, 3, 6, 6, 1]])

<br>
Iterate by row:

In [417]:
for row in test:
    print(row)

[8 0 1 8 7 5 7 6 4 6]
[5 2 2 6 3 7 8 6 1 2]
[6 7 7 1 1 5 1 3 5 4]
[1 5 4 2 0 8 3 6 6 1]


<br>
Iterate by index:

In [418]:
for i in range(len(test)):
    print(test[i])

[8 0 1 8 7 5 7 6 4 6]
[5 2 2 6 3 7 8 6 1 2]
[6 7 7 1 1 5 1 3 5 4]
[1 5 4 2 0 8 3 6 6 1]


<br>
Iterate by row and index:

In [420]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [8 0 1 8 7 5 7 6 4 6]
row 1 is [5 2 2 6 3 7 8 6 1 2]
row 2 is [6 7 7 1 1 5 1 3 5 4]
row 3 is [1 5 4 2 0 8 3 6 6 1]


<br>
Use `zip` to iterate over multiple iterables.

In [421]:
test2 = test**2
test2

array([[64,  0,  1, 64, 49, 25, 49, 36, 16, 36],
       [25,  4,  4, 36,  9, 49, 64, 36,  1,  4],
       [36, 49, 49,  1,  1, 25,  1,  9, 25, 16],
       [ 1, 25, 16,  4,  0, 64,  9, 36, 36,  1]], dtype=int32)

In [424]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[8 0 1 8 7 5 7 6 4 6] + [64  0  1 64 49 25 49 36 16 36] = [72  0  2 72 56 30 56 42 20 42]
[5 2 2 6 3 7 8 6 1 2] + [25  4  4 36  9 49 64 36  1  4] = [30  6  6 42 12 56 72 42  2  6]
[6 7 7 1 1 5 1 3 5 4] + [36 49 49  1  1 25  1  9 25 16] = [42 56 56  2  2 30  2 12 30 20]
[1 5 4 2 0 8 3 6 6 1] + [ 1 25 16  4  0 64  9 36 36  1] = [ 2 30 20  6  0 72 12 42 42  2]


In [427]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [429]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [430]:
for i, j in zip(a, b):
    print(i,'+',j,'=',i+j)

[1. 1. 1.] + [0. 0. 0.] = [1. 1. 1.]
[1. 1. 1.] + [0. 0. 0.] = [1. 1. 1.]


In [423]:
x=1
y=2
x+y

3

In [21]:
import datetime as dt

In [23]:
import time as tm

In [36]:
print(tm.time())
dt.datetime.fromtimestamp(tm.time())

1604134028.7306664


datetime.datetime(2020, 10, 31, 16, 47, 8, 730666)

In [32]:
delta = dt.timedelta(100)
delta

datetime.timedelta(days=100)

In [34]:
today = dt.date.today()
today-delta

datetime.date(2020, 7, 23)

In [35]:
today > today - delta

True